# Generated by Django 3.2.10 on 2023-07-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_newsarticle_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='author',
        ),
    ]
