# Generated by Django 3.2.10 on 2023-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_remove_newsarticle_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(default='xasd', max_length=200),
            preserve_default=False,
        ),
    ]
