# Generated by Django 3.2.10 on 2023-07-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_newsarticle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.user'),
        ),
    ]
