# Generated by Django 3.2.10 on 2023-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_newsarticle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
